[project]
name = "likerogue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "salmonella", email = "xahit1337@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pyray>=0.1.0",
    "raylib>=6.0.1.0",
]

[project.scripts]
likerogue = "likerogue:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
